name: Deploy to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때마다 배포

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}  

      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -r ./build/libs/demo-0.0.1-SNAPSHOT.jar ec2-user@13.125.45.19:~/demo-0.0.1-SNAPSHOT.jar

      - name: Restart application
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@13.125.45.19 "pkill -f 'java -jar demo-0.0.1-SNAPSHOT.jar' || true"
          ssh -o StrictHostKeyChecking=no ec2-user@13.125.45.19 "java -jar ~/demo-0.0.1-SNAPSHOT.jar &"
